name: WildThink
favicon: null
layout_spectrum: 0.9747240643482655
typography_spectrum: 0.10153040522709489
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.28686619736254215
  lightness: 0.9167424375191331
  saturation: 0.5382184761110693
  rhythmicContrast: 0.9305412981193513
purpose: []
